services:
  cms-web-dev:
    build: .
    container_name: cms-web-dev
    restart: unless-stopped
    networks:
      - hosting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-web-dev.rule=Host(`cms-dev.zunkireelabs.com`)"
      - "traefik.http.routers.cms-web-dev.entrypoints=websecure"
      - "traefik.http.routers.cms-web-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.cms-web-dev.loadbalancer.server.port=80"

networks:
  hosting:
    external: true
