services:
  cms-web-dev:
    image: ghcr.io/zunkireelabs/cms-web-dev:main
    container_name: cms-web-dev
    restart: unless-stopped
    environment:
      - CMS_URL=${CMS_URL:-}
      - REVALIDATE_SECRET=${REVALIDATE_SECRET:-}
    networks:
      - hosting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-web-dev.rule=Host(`cmstnc.com`) || Host(`www.cmstnc.com`) || Host(`cms-dev.zunkireelabs.com`)"
      - "traefik.http.routers.cms-web-dev.entrypoints=websecure"
      - "traefik.http.routers.cms-web-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.cms-web-dev.loadbalancer.server.port=3000"

networks:
  hosting:
    external: true
