services:
  cms-web-stage:
    image: ghcr.io/zunkireelabs/cms-web-dev:stage
    container_name: cms-web-stage
    restart: unless-stopped
    environment:
      - CMS_URL=${CMS_URL:-}
      - REVALIDATE_SECRET=${REVALIDATE_SECRET:-}
    networks:
      - hosting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms-web-stage.rule=Host(`stage-branch.zunkireelabs.com`)"
      - "traefik.http.routers.cms-web-stage.entrypoints=websecure"
      - "traefik.http.routers.cms-web-stage.tls.certresolver=letsencrypt"
      - "traefik.http.services.cms-web-stage.loadbalancer.server.port=3000"

networks:
  hosting:
    external: true
